name: Thermolog
options:
  bundleIdPrefix: com.shimondeitel.bedroomtemplog
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  groupSortPosition: top
settings:
  base:
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.0"
    DEVELOPMENT_TEAM: "W7Q885Q59C"
    CODE_SIGN_STYLE: Automatic
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: "YES"
targets:
  Thermolog:
    type: application
    platform: iOS
    sources:
      - path: Thermolog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bedroomtemplog
        TARGETED_DEVICE_FAMILY: "1"
        INFOPLIST_FILE: Thermolog/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ENABLE_PREVIEWS: "YES"
        GENERATE_INFOPLIST_FILE: "NO"
  ThermologTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: ThermologTests
      - path: Thermolog.storekit
    dependencies:
      - target: Thermolog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bedroomtemplog.tests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
  ThermologUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: ThermologUITests
    dependencies:
      - target: Thermolog
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shimondeitel.bedroomtemplog.uitests
        GENERATE_INFOPLIST_FILE: "YES"
        TARGETED_DEVICE_FAMILY: "1"
schemes:
  Thermolog:
    build:
      targets:
        Thermolog: all
        ThermologTests: [test]
        ThermologUITests: [test]
    run:
      config: Debug
      storeKitConfiguration: Thermolog.storekit
    test:
      config: Debug
      storeKitConfiguration: Thermolog.storekit
      targets:
        - ThermologTests
        - ThermologUITests
    archive:
      config: Release
